/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewProductRouteImport } from './routes/new-product'
import { Route as IndexRouteImport } from './routes/index'

const NewProductRoute = NewProductRouteImport.update({
  id: '/new-product',
  path: '/new-product',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new-product': typeof NewProductRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new-product': typeof NewProductRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new-product': typeof NewProductRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/new-product'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new-product'
  id: '__root__' | '/' | '/new-product'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewProductRoute: typeof NewProductRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new-product': {
      id: '/new-product'
      path: '/new-product'
      fullPath: '/new-product'
      preLoaderRoute: typeof NewProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewProductRoute: NewProductRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
